``` mermaid
flowchart LR

subgraph 0["packages"]
subgraph 1["api-client"]
subgraph 2["src"]
subgraph 3["generated"]
subgraph 4["model"]
5["createRecordRequest.ts"]
6["errorResponse.ts"]
7["index.ts"]
8["listRecordsParams.ts"]
9["masterMeta.ts"]
A["masterMetaField.ts"]
B["masterMetaFieldType.ts"]
C["masterRecord.ts"]
D["paging.ts"]
E["recordPage.ts"]
F["updateRecordRequest.ts"]
end
G["poc.ts"]
end
end
end
end
subgraph H["services"]
subgraph I["master"]
subgraph J["web"]
subgraph K["src"]
subgraph L["app"]
M["recordsRoute.ts"]
end
subgraph N["features"]
subgraph O["masterRecords"]
P["recordsView.ts"]
end
end
end
end
end
end
7-->5
7-->6
7-->8
7-->9
7-->A
7-->B
7-->C
7-->D
7-->E
7-->F
9-->A
A-->B
E-->C
E-->D
G-->7
M-->P
P-->C
P-->G

```